# Generated by Django 2.2.6 on 2022-09-12 18:23

import Students.models
import constrainedfilefield.fields.file
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateTimeField()),
                ('placeofbirth', models.CharField(blank=True, max_length=80, null=True)),
                ('finishedschool', models.CharField(blank=True, max_length=80, null=True)),
                ('application', constrainedfilefield.fields.file.ConstrainedFileField(blank=True, js_checker=True, max_upload_size=2621440, mime_lookup_length=4096, null=True, upload_to=Students.models.uplodad_location_application)),
                ('courseselection', models.CharField(blank=True, choices=[('Tehnološki', 'Tehnološki'), ('Informatički', 'Informatički'), ('Matematički', 'Matematički')], default='Informatički', max_length=40)),
                ('endcertificate', constrainedfilefield.fields.file.ConstrainedFileField(blank=True, js_checker=True, max_upload_size=2621440, mime_lookup_length=4096, null=True, upload_to=Students.models.uplodad_location_certificate)),
                ('gradeaverage', models.DecimalField(decimal_places=2, default=3.0, max_digits=4)),
                ('totalgraduationgrade', models.DecimalField(decimal_places=2, default=3.0, max_digits=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
