# Generated by Django 2.2.6 on 2022-09-12 21:58

import Students.models
import constrainedfilefield.fields.file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_auto_20220912_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informaticcourse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mathcourse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='application',
            field=constrainedfilefield.fields.file.ConstrainedFileField(js_checker=True, max_upload_size=2621440, mime_lookup_length=4096, null=True, upload_to=Students.models.uplodad_location_application),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='courseselection',
            field=models.CharField(choices=[('Tehnološki', 'Tehnološki'), ('Informatički', 'Informatički'), ('Matematički', 'Matematički')], default='Informatički', max_length=40),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='endcertificate',
            field=constrainedfilefield.fields.file.ConstrainedFileField(js_checker=True, max_upload_size=2621440, mime_lookup_length=4096, null=True, upload_to=Students.models.uplodad_location_certificate),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='finishedschool',
            field=models.CharField(default='nije zavrsio', max_length=80),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='placeofbirth',
            field=models.CharField(default='Zagreb', max_length=80),
        ),
        migrations.AlterField(
            model_name='techcourse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
