# Generated by Django 2.2.6 on 2022-09-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_auto_20220913_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='name',
            field=models.CharField(default='Pero', max_length=80),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='surname',
            field=models.CharField(default='Perice', max_length=80),
        ),
    ]
